"""empty message

Revision ID: 12bbeec762fe
Revises: d97cb4ae06d1
Create Date: 2016-03-19 18:23:09.619637

"""

# revision identifiers, used by Alembic.
revision = '12bbeec762fe'
down_revision = 'd97cb4ae06d1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('account', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_pkey')
    )
    op.drop_table('account')
    ### end Alembic commands ###
