"""empty message

Revision ID: 1970174d2c01
Revises: de7cdb2ba63a
Create Date: 2016-03-25 20:47:21.806444

"""

# revision identifiers, used by Alembic.
revision = '1970174d2c01'
down_revision = 'de7cdb2ba63a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster')
    op.drop_table('reviews')
    op.drop_index('account_accountb_idx', table_name='account')
    op.add_column('player', sa.Column('playerb', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'playerb')
    op.create_index('account_accountb_idx', 'account', ['accountb'], unique=False)
    op.create_table('reviews',
    sa.Column('review', postgresql.JSONB(), autoincrement=False, nullable=True)
    )
    op.create_table('monster',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monster', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='monster_pkey')
    )
    ### end Alembic commands ###
