"""empty message

Revision ID: 20f5c853f2b0
Revises: None
Create Date: 2016-03-27 15:57:01.523613

"""

# revision identifiers, used by Alembic.
revision = '20f5c853f2b0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('account', postgresql.JSON(), nullable=True),
    sa.Column('accountb', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('player', postgresql.JSON(), nullable=True),
    sa.Column('playerb', postgresql.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('account')
    ### end Alembic commands ###
