"""empty message

Revision ID: 3c3d7ca2226d
Revises: None
Create Date: 2016-03-08 22:07:58.305398

"""

# revision identifiers, used by Alembic.
revision = '3c3d7ca2226d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    ### end Alembic commands ###
