"""empty message

Revision ID: 3e2faa2271d8
Revises: 3c3d7ca2226d
Create Date: 2016-03-11 21:26:40.200344

"""

# revision identifiers, used by Alembic.
revision = '3e2faa2271d8'
down_revision = '3c3d7ca2226d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster')
    ### end Alembic commands ###
