"""empty message

Revision ID: 6717968c5203
Revises: 20f5c853f2b0
Create Date: 2016-04-04 16:23:54.101963

"""

# revision identifiers, used by Alembic.
revision = '6717968c5203'
down_revision = '20f5c853f2b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('king',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('king_flag', sa.Boolean(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('king')
    ### end Alembic commands ###
