"""empty message

Revision ID: 6cdef5b68ace
Revises: 1970174d2c01
Create Date: 2016-03-25 21:27:08.102181

"""

# revision identifiers, used by Alembic.
revision = '6cdef5b68ace'
down_revision = '1970174d2c01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('account_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'account_id')
    ### end Alembic commands ###
