"""empty message

Revision ID: d97cb4ae06d1
Revises: 3e2faa2271d8
Create Date: 2016-03-12 00:01:41.453038

"""

# revision identifiers, used by Alembic.
revision = 'd97cb4ae06d1'
down_revision = '3e2faa2271d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    ### end Alembic commands ###
